# example values

indexing-settings:
  sites:
    - url: https://www.skillbox.ru
      name: skillbox
    - url: https://www.playback.ru
      name: playBack.ru
    - url: https://www.lenta.ru
      name: lenta.ru

server:
  port: 8081

spring:
  datasource:
    username: root
    password: Romakat77
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      SET: FOREIGN_KEY_CHECKS=0;
      ddl-auto: create
    show-sql: true
    ON : DELETE SET NULL



#server:
#  servlet:
#    context-path: /admin


#logging:
#  level:
#    org.springframework.web:  FINEST
#    org.apache:  FINEST
#    org.hibernate:  FINEST
