# example values
indexing-settings:
  sites:
    - url: https://www.skillbox.ru
      name: skillbox.ru
    - url: https://www.playback.ru
      name: playBack.ru
    - url: https://upakmarket.com
      name: upakmarket.com

server:
  port: 8081

spring:
  datasource:
    username: root
    password: romakat77
    url: jdbc:postgresql://localhost:5432/search_engine
    driver-class-name: org.postgresql.Driver
jpa:
  properties:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect

    SET: FOREIGN_KEY_CHECKS=0;

  show-sql: true
  ON : DELETE SET NULL

#server:
#  servlet:
#    context-path: /admin


#logging:
#  level:
#    org.springframework.web:  FINEST
#    org.apache:  FINEST
#    org.hibernate:  FINEST
